spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/crudpessoa}
    username: ${SPRING_DATASOURCE_USERNAME:crudpessoa}
    password: ${SPRING_DATASOURCE_PASSWORD:crudpessoa}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: crud-pessoa
